# примеры API-запросов
@baseUrl = http://localhost:8000/adv/

GET {{baseUrl}}

###

GET {{baseUrl}}
Authorization: Token 793cfd15235331e67ab091b9c4de979665d74be0

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: Token 793cfd15235331e67ab091b9c4de979665d74be0


{
  "text": "объявление. Тест с токеном."
}

###

DELETE {{baseUrl}}/5/
Authorization: Token 793cfd15235331e67ab091b9c4de979665d74be0
###

GET {{baseUrl}}/8/
Authorization: Token 793cfd15235331e67ab091b9c4de979665d74be0

###

PATCH {{baseUrl}}/9/
Content-Type: application/json
Authorization: Token 793cfd15235331e67ab091b9c4de979665d74be0

{
  "opened": false
}

###

PUT {{baseUrl}}/9/
Content-Type: application/json
Authorization: Token 793cfd15235331e67ab091b9c4de979665d74be0

{
  "text": "объявление с токеном. замена текста и статуса ",
  "opened": false
}


