# Generated by Django 6.0.2 on 2026-02-28 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_rename_adv_advertisement"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 28, 15, 24, 54, 470335, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advertisement",
            name="opened",
            field=models.BooleanField(default=True),
        ),
    ]
